/**
 * The season-2026 corpus as a scenario baseline, plus the branches the build
 * plan names.
 *
 * **Direction of the arrow: fixtures -> scenario.** This module takes the
 * already-parsed season object and the already-built adapter inputs, and
 * imports nothing from `packages/core/src/fixtures/`. It re-parses no CSV: a
 * second reading of the em dash in the Summit HS 09/19 row, or of the "schedule
 * as 90" note in `game_formats.csv`, would be free to disagree with the first.
 *
 * ## Which venue the acceptance test withdraws, and why that one
 *
 * The build plan asks for *"no venue X"*, built from the fixture baseline and
 * diffed, with the report naming *"the affected format, the replacement venues,
 * and the added compromises"*. Only one venue in this corpus produces that
 * report, and the others fail for stated reasons:
 *
 * | venue | why not |
 * | --- | --- |
 * | Maplewood Back (5v5) | the only 5v5 ground in the corpus — removal has no replacement at all |
 * | Orchard Park (4v4) | the only 4v4 ground, and the Minis sessions' home |
 * | Alder Park | two formats plus the corpus's only `overlap_pairs`; removing it deletes incident 3's machinery |
 * | Maplewood Front (7v7) | a single clean replacement grade, so there are no *added compromises* to report |
 * | Summit HS / Riverbend | 11v11 only, and the Select layer is not what the acceptance test is about |
 *
 * **Brookside Park** is the one that works: 72 games, all 7v7, on nine
 * Saturdays, 100% of its use. Withdrawing it produces an unambiguous affected
 * format, *two grades* of replacement — Maplewood Front Field 1 is
 * `sizes: ["7v7"] lined: ["7v7"]` and clean but already carries 54 games; Alder
 * Pitch 1A/1B/4A/4B are `sizes: ["9v9"] lined: ["9v9"]`, size-allowed for 7v7
 * under the downward-closed policy and lining-mismatched — and added compromises
 * generated by the corpus rather than constructed. It also keeps the machinery
 * live: those Alder halves overlap Pitch 2 and Pitch 3 where the 11v11 layer
 * sits, so some games legitimately have nowhere to go. That is incident 10,
 * which the fixture README describes as arising *"in a reduced-venue scenario"*.
 *
 * Nothing above is hardcoded below. `season2026VenueUnavailableScenario()`
 * takes the venue id, and every figure in `tests/scenarioBranching.test.js` is
 * derived from the corpus at test time.
 *
 * @module scenario/adapters/season2026Scenarios
 */

import { SEASON_2026_EARLIEST_KICKOFF_MINUTES } from '../../reserve/adapters/season2026Reserve.js';

import { makeSeasonInputs } from '../inputs.js';
import { replacementSurfacesFor } from '../relocation.js';
import { SCENARIO_OVERRIDE_KIND } from '../reasonCodes.js';
import { makeScenario } from '../scenario.js';

/**
 * How far apart the proposer lays its candidate kickoffs.
 *
 * The **format block**, read from the timing table at call time rather than
 * written here: `game_formats.csv` says 7v7 blocks at 75 minutes and the
 * published Brookside kickoffs are 75 minutes apart, so a grid on any other
 * cadence would offer slots the club has never used. This constant is only the
 * fallback for a format the table cannot bound.
 */
export const SEASON_2026_RELOCATION_CADENCE_MINUTES = 75;

/** What a relocation policy built here cites as its provenance. */
export const SEASON_2026_RELOCATION_POLICY_SOURCE =
  'fixtures/season-2026: the format block from game_formats.csv, the earliest kickoff the published season gives the format, and every leaf surface within one size grade of it';

/**
 * The corpus as one immutable baseline bundle.
 *
 * @param {Object} input
 * @param {import('../../ruleEngine/types.js').Schedule} input.schedule - `toSeason2026Schedule()`
 * @param {Object} input.facilityInput - `toSeason2026FacilityGraphInput()`
 * @param {Object} input.timingInput - `toFormatTimingInput()`
 * @param {Object} input.calendarInput - `toAvailabilityCalendarInput()`
 * @param {ReadonlyArray<Object>} input.constraints - the seeded constraint records
 * @param {ReadonlyArray<Object>} [input.waivers]
 * @param {ReadonlyArray<Object>} [input.reservedSlots]
 * @param {Object} [input.venueComplexes]
 * @param {string} [input.id]
 * @returns {import('../types.js').SeasonInputs}
 */
export function season2026SeasonInputs(input) {
  // The equipment windows live beside the other record arrays, not inside the
  // facility input: "the 9v9 goals are not at Alder on 08/22" is one of the
  // three branches the build plan names, so it has to be a record set an
  // override can edit. `makeSeasonInputs()` refuses the other arrangement.
  const { equipmentWindows = [], ...facilityInput } = /** @type {Record<string, any>} */ (
    input.facilityInput
  );

  return makeSeasonInputs({
    id: input.id ?? 'season-2026',
    label: 'season-2026 published baseline',
    schedule: input.schedule,
    facilityInput,
    timingInput: input.timingInput,
    permits: input.calendarInput.permitWindows,
    sunsets: input.calendarInput.sunsets,
    lighting: input.calendarInput.lighting ?? [],
    equipment: equipmentWindows,
    constraints: input.constraints,
    waivers: input.waivers ?? [],
    reservedSlots: input.reservedSlots ?? [],
    registry: { name: 'season-2026', source: 'fixtures/season-2026 + the incident log' },
    calendarOptions: {
      sunsetMarginMinutes: input.calendarInput.sunsetMarginMinutes,
      permitMarginMinutes: input.calendarInput.permitMarginMinutes,
      source: input.calendarInput.source ?? null,
    },
    venueComplexes: input.venueComplexes ?? {},
  });
}

/**
 * "No venue X" as a branch: **one record with a `venueId`**.
 *
 * Not five hand-written blackouts. The materialiser expands this into one
 * blackout per weekday and withdraws the venue's own permit rows as it goes, so
 * the branch's correctness does not depend on the author having enumerated
 * every weekday and every date exception — and the calendar never reports
 * `PERMIT_PRECEDENCE_AMBIGUOUS` for a blackout laid beside an open window.
 *
 * @param {Object} input
 * @param {string} input.venueId
 * @param {string} input.baselineId
 * @param {string} input.requestedBy
 * @param {string} [input.id]
 * @param {string} [input.name]
 * @param {string} [input.rationale]
 * @param {ReadonlyArray<string>|null} [input.dates] - null withdraws the venue for the whole season
 * @param {string|null} [input.at] - a naive timestamp, supplied; nothing here reads a clock
 * @param {string|null} [input.parentScenarioId]
 * @returns {import('../types.js').ScheduleScenario}
 */
export function season2026VenueUnavailableScenario(input) {
  const scope =
    input.dates === null || input.dates === undefined ? 'the whole season' : input.dates.join(', ');
  return makeScenario({
    id: input.id ?? `no-${input.venueId}`,
    name: input.name ?? `without ${input.venueId}`,
    baselineId: input.baselineId,
    parentScenarioId: input.parentScenarioId ?? null,
    rationale:
      input.rationale ??
      `the club may lose ${input.venueId} for ${scope}; this branch answers what that costs, which games move, which constraints break and how much ground is left`,
    requestedBy: input.requestedBy,
    createdAt: input.at ?? null,
    overrides: [
      {
        kind: SCENARIO_OVERRIDE_KIND.VENUE_UNAVAILABLE,
        venueId: input.venueId,
        dates: input.dates ?? null,
        by: input.requestedBy,
        at: input.at ?? null,
        reason: `${input.venueId} is unavailable for ${scope}`,
      },
    ],
  });
}

/**
 * Where the candidate grid is anchored for one format.
 *
 * **The earliest kickoff the published season actually gives this format**, and
 * not the club's blanket first kickoff. The two are different numbers here —
 * `SEASON_2026_EARLIEST_KICKOFF_MINUTES` is 08:00 and the earliest 7v7 kickoff
 * in the corpus is 09:00 — and the difference matters, because a grid laid at a
 * cadence of the format's own block from the wrong anchor lands **between**
 * every published kickoff. Every relocated game would then be offered a time the
 * club has never used, and no game could keep the time families already have.
 *
 * The blanket constant is the fallback, for a format the schedule holds no row
 * of; a caller with a stated policy of its own passes `earliestKickoffMinutes`.
 *
 * @param {ReadonlyArray<Object>} games - the baseline schedule's rows
 * @param {string} format
 * @returns {number}
 */
export function season2026EarliestKickoffFor(games, format) {
  const kickoffs = games
    .filter((game) => game.format === format)
    .map((game) => Number(game.startMinutes));
  if (kickoffs.length === 0) return SEASON_2026_EARLIEST_KICKOFF_MINUTES;
  return Math.min(...kickoffs);
}

/**
 * The relocation policy for one format, derived from the corpus.
 *
 * Every number has a stated source: the cadence is the format's own
 * `blockMinutes` from `game_formats.csv`, the anchor is
 * {@link season2026EarliestKickoffFor}, and the candidate ground is
 * {@link replacementSurfacesFor} over the graph.
 *
 * @param {Object} input
 * @param {import('../../facility/types.js').FacilityGraph} input.graph
 * @param {import('../../timing/types.js').FormatTimingTable} input.table
 * @param {string} input.format
 * @param {ReadonlyArray<string>} input.excludeVenueIds
 * @param {ReadonlyArray<Object>} input.games - the baseline schedule's rows, for the anchor
 * @param {number} [input.earliestKickoffMinutes] - a stated anchor, overriding the derived one
 * @returns {Object} input for `RelocationPolicySchema`
 */
export function season2026RelocationPolicy(input) {
  const timing = input.table.formats?.[input.format] ?? null;
  const cadence = timing?.blockMinutes ?? SEASON_2026_RELOCATION_CADENCE_MINUTES;
  return {
    surfaceIds: replacementSurfacesFor(input.graph, {
      format: input.format,
      excludeVenueIds: input.excludeVenueIds,
      maxGradesAbove: 1,
    }),
    cadenceMinutes: cadence,
    earliestKickoffMinutes:
      input.earliestKickoffMinutes ?? season2026EarliestKickoffFor(input.games, input.format),
    source: SEASON_2026_RELOCATION_POLICY_SOURCE,
  };
}

/**
 * Capacity subjects for the diff — **stated, because there is no season-wide
 * capacity number**.
 *
 * `ReserveCapacityInputSchema` requires a format, a surface set, a date set, a
 * first kickoff and a requirement before it has an answer, so a caller declares
 * what it wants counted. One subject per format is the useful default for a
 * venue withdrawal: the question is "how much 7v7 ground is left", not "how
 * much ground".
 *
 * @param {Object} input
 * @param {import('../../facility/types.js').FacilityGraph} input.graph
 * @param {import('../../timing/types.js').FormatTimingTable} input.table
 * @param {string} input.format
 * @param {ReadonlyArray<string>} input.dates
 * @param {ReadonlyArray<string>} input.surfaceIds
 * @param {{ slots: number, label: string, source: string }} input.requirement
 * @param {ReadonlyArray<Object>} input.games - the baseline schedule's rows, for the anchor
 * @param {number} [input.earliestKickoffMinutes]
 * @returns {Object[]}
 */
export function season2026CapacitySubjects(input) {
  const timing = input.table.formats?.[input.format] ?? null;
  return [
    {
      name: `${input.format} ground across ${input.dates.length} date(s)`,
      format: input.format,
      dates: [...input.dates],
      surfaceIds: [...input.surfaceIds],
      cadenceMinutes: timing?.blockMinutes ?? SEASON_2026_RELOCATION_CADENCE_MINUTES,
      // The same anchor the relocation policy uses, so the two numbers are
      // about the same grid. Two capacity reports laid at different anchors are
      // not comparable and their difference is not a delta.
      earliestKickoffMinutes:
        input.earliestKickoffMinutes ?? season2026EarliestKickoffFor(input.games, input.format),
      requirement: input.requirement,
      reservedSlots: [],
      bookings: [],
    },
  ];
}
