#!/usr/bin/env python3
"""Regenerate the heat-forecast reference data from pvlib and the Python
reference implementation (scripts/heat/reference/cvsc_wbgt.py).

Run it only when the reference itself is meant to change. Nothing here runs in
CI; the JS port is tested against what this script wrote.

    pip install pvlib h5py
    python3 scripts/heat/generate_heat_reference.py

Writes:

* packages/core/src/heat/spaTables.js -- the NREL SPA periodic-term tables
  (Reda & Andreas 2004, Tables A4.2 and A4.3) exactly as pvlib's spa.py
  carries them, so no coefficient is hand-transcribed.
* packages/core/src/heat/data/linkeTurbidity-nws-0p5deg.bin -- pvlib's monthly
  Linke turbidity climatology (LinkeTurbidities.h5, 1/12 degree, global),
  block-averaged to 0.5 degree over the NWS forecast box 15..72 N, 180..60 W.
  Layout: uint8, month-major [12][114][240], row 0 = the band just south of
  72 N, column 0 = the band just east of 180 W; value = 20 x TL (pvlib's own
  encoding).
* tests/fixtures/heat/gridpoint-mtr-2026-10-03.json -- the reference test's
  offline gridpoint fixture, plus gridpoint metadata (see FIXTURE_META).
* tests/fixtures/heat/heatReference.json -- golden values: every hour of the
  fixture day for every reference site, computed twice (pvlib's native
  turbidity lookup, and the 0.5-degree table the JS port ships), plus solar
  position and turbidity samples.
"""
from __future__ import annotations

import json
import math
import os
import sys
from datetime import date

import h5py
import numpy as np
import pandas as pd
import pvlib
from pvlib import spa

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, '..', '..'))
sys.path.insert(0, os.path.join(HERE, 'reference'))

import cvsc_wbgt as ref  # noqa: E402
from test_cvsc_wbgt import fixture  # noqa: E402

TL_RES = 0.5
TL_NORTH, TL_SOUTH, TL_WEST, TL_EAST = 72.0, 15.0, -180.0, -60.0

# The reference fixture carries only the four layers and elevation. The JS
# client validates the gridpoint metadata a live response carries (field names
# confirmed against a live MTR response on 2026-10-02), so the fixture gets the
# values the fixture's own docstring states: MTR forecast issued 2026-10-02
# 01:31 PDT (08:31 UTC), grid MTR/97,99.
FIXTURE_META = {
    '@id': 'https://api.weather.gov/gridpoints/MTR/97,99',
    '@type': 'wx:Gridpoint',
    'updateTime': '2026-10-02T08:31:00+00:00',
    'validTimes': '2026-10-03T07:00:00+00:00/P1D',
    'forecastOffice': 'https://api.weather.gov/offices/MTR',
    'gridId': 'MTR',
    'gridX': 97,
    'gridY': 99,
}


def write(rel, text_or_bytes):
    path = os.path.join(REPO, rel)
    os.makedirs(os.path.dirname(path), exist_ok=True)
    mode = 'wb' if isinstance(text_or_bytes, bytes) else 'w'
    with open(path, mode) as fh:
        fh.write(text_or_bytes)
    print('wrote', rel)


def js_rows(arr):
    return '\n'.join('  [' + ', '.join(repr(float(x)) for x in row) + '],' for row in arr)


def spa_tables():
    names = ['L0', 'L1', 'L2', 'L3', 'L4', 'L5', 'B0', 'B1', 'R0', 'R1', 'R2', 'R3', 'R4']
    out = [
        '/**',
        ' * NREL Solar Position Algorithm periodic terms (Reda & Andreas 2004,',
        ' * Tables A4.2 and A4.3), as carried by pvlib ' + pvlib.__version__ + ' `pvlib/spa.py`.',
        ' *',
        ' * GENERATED by scripts/heat/generate_heat_reference.py -- do not edit.',
        ' * Each earth-periodic row is [A, B, C]: the term A * cos(B + C * JME).',
        ' *',
        ' * @module heat/spaTables',
        ' */',
        '',
    ]
    for n in names:
        out.append(f'/** @type {{ReadonlyArray<ReadonlyArray<number>>}} */')
        out.append(f'export const {n} = [')
        out.append(js_rows(getattr(spa, n)))
        out.append('];')
        out.append('')
    out.append('/** Nutation [a, b, c, d] per row (Table A4.3). */')
    out.append('export const NUTATION_ABCD = [')
    out.append(js_rows(spa.NUTATION_ABCD_ARRAY))
    out.append('];')
    out.append('')
    out.append('/** Nutation Y-terms per row (Table A4.3). */')
    out.append('export const NUTATION_Y = [')
    out.append(js_rows(spa.NUTATION_YTERM_ARRAY))
    out.append('];')
    out.append('')
    return '\n'.join(out)


def turbidity_table():
    path = os.path.join(os.path.dirname(pvlib.__file__), 'data', 'LinkeTurbidities.h5')
    with h5py.File(path, 'r') as f:
        native = f['LinkeTurbidity'][:].astype(float)
    k = int(round(TL_RES * 12))
    r0 = int(round((90 - TL_NORTH) * 12))
    r1 = int(round((90 - TL_SOUTH) * 12))
    c0 = int(round((TL_WEST + 180) * 12))
    c1 = int(round((TL_EAST + 180) * 12))
    sub = native[r0:r1, c0:c1, :]
    rows, cols = sub.shape[0] // k, sub.shape[1] // k
    blk = sub.reshape(rows, k, cols, k, 12).mean(axis=(1, 3))
    table = np.rint(blk).astype(np.uint8)  # still 20 x TL
    return table, rows, cols


def table_tl_series(table, lat, lon, times):
    """pvlib's monthly->daily interpolation over the 0.5-degree cell."""
    r = int((TL_NORTH - lat) // TL_RES)
    c = int((lon - TL_WEST) // TL_RES)
    lts = table[r, c, :].astype(float)
    return pvlib.clearsky._interpolate_turbidity(lts, times) / 20.0


def run_reference(table=None, category=1):
    """compute_site for every site, every hour; optionally with the table TL."""
    orig = pvlib.location.Location.get_clearsky

    def patched(self, times, model='ineichen', **kw):
        tl = table_tl_series(table, self.latitude, self.longitude, times)
        return orig(self, times, model=model, linke_turbidity=tl, **kw)

    if table is not None:
        pvlib.location.Location.get_clearsky = patched
    try:
        out = {}
        for s in ref.SITES:
            rows = ref.compute_site(s, fixture(), date(2026, 10, 3), list(range(24)), category)
            out[s.key] = [
                {k: (None if isinstance(v, float) and math.isnan(v) else v) for k, v in r.items()}
                for r in rows
            ]
        return out
    finally:
        pvlib.location.Location.get_clearsky = orig


def unrounded_rows(table):
    """Full-precision WBGT and trigger values, so the JS port can be held tight."""
    out = {}
    for s in ref.SITES:
        local = pd.DatetimeIndex([pd.Timestamp(f'2026-10-03 {h:02d}:00', tz=ref.TZ) for h in range(24)])
        loc = pvlib.location.Location(s.lat, s.lon, tz=ref.TZ, altitude=121.0)
        sp = loc.get_solarposition(local)
        tl_native = pvlib.clearsky.lookup_linke_turbidity(local, s.lat, s.lon)
        tl_table = table_tl_series(table, s.lat, s.lon, local)
        cs_native = loc.get_clearsky(local, model='ineichen')
        cs_table = loc.get_clearsky(local, model='ineichen', linke_turbidity=tl_table)
        p_hpa = ref.station_pressure_hpa(121.0)
        g = fixture()['properties']
        temp = ref.expand(g['temperature'], 't')
        dew = ref.expand(g['dewpoint'], 'd')
        wind = ref.expand(g['windSpeed'], 'w')
        sky = ref.expand(g['skyCover'], 's')
        rows = []
        for h, t_loc in enumerate(local):
            t_utc = t_loc.tz_convert('UTC')
            n = sky[t_utc] / 100.0
            zen = math.radians(float(sp.loc[t_loc, 'apparent_zenith']))
            T, Td, W = temp[t_utc], dew[t_utc], wind[t_utc]
            row = {
                'hour': h,
                'utc': t_utc.isoformat(),
                'airF': T, 'dewF': Td, 'windMph': W, 'skyPct': float(sky[t_utc]),
                'zenith': float(sp.loc[t_loc, 'zenith']),
                'apparentZenith': float(sp.loc[t_loc, 'apparent_zenith']),
                'tlNative': float(tl_native.loc[t_loc]),
                'tlTable': float(tl_table.loc[t_loc]),
            }
            for tag, cs in (('Native', cs_native), ('Table', cs_table)):
                ghi = float(cs.loc[t_loc, 'ghi']) * (1 - 0.75 * n ** 3.4)
                w = ref.field_wbgt(s.surface, T, Td, W, ghi, zen, h, p_hpa)
                row['clearGhi' + tag] = float(cs.loc[t_loc, 'ghi'])
                row['ghi' + tag] = ghi
                row['wbgt' + tag] = w
                for cat in (1, 2, 3):
                    red = ref.BANDS[cat][2][1] + 0.1
                    black = ref.BANDS[cat][3][1]
                    r_ = ref.air_trigger(s.surface, red, Td, W, ghi, zen, h, p_hpa)
                    b_ = ref.air_trigger(s.surface, black, Td, W, ghi, zen, h, p_hpa)
                    row[f'red{tag}Cat{cat}'] = None if math.isnan(r_) else r_
                    row[f'black{tag}Cat{cat}'] = None if math.isnan(b_) else b_
            rows.append(row)
        out[s.key] = {'lat': s.lat, 'lon': s.lon, 'surface': s.surface, 'name': s.name, 'rows': rows}
    return out


def solar_samples():
    """SPA samples on a plain grid (no named places), low sun included."""
    rng = np.random.default_rng(20261003)
    samples = []
    lats = [-45.0, -15.0, 0.0, 15.0, 30.0, 37.5, 45.0, 60.0, 70.0]
    for i in range(160):
        lat = float(lats[i % len(lats)])
        lon = float(np.round(rng.uniform(-179.5, 179.5), 2))
        elev = float(np.round(rng.uniform(0, 2500), 1))
        ts = pd.Timestamp('2026-01-01T00:00:00Z') + pd.Timedelta(minutes=int(rng.integers(0, 525600 * 2)))
        idx = pd.DatetimeIndex([ts])
        pressure = pvlib.atmosphere.alt2pres(elev)
        sp = pvlib.solarposition.get_solarposition(idx, lat, lon, altitude=elev, pressure=pressure, temperature=12)
        samples.append({
            'utc': ts.isoformat(), 'lat': lat, 'lon': lon, 'elevation': elev,
            'pressurePa': float(pressure),
            'zenith': float(sp['zenith'].iloc[0]),
            'apparentZenith': float(sp['apparent_zenith'].iloc[0]),
        })
    return samples


def clearsky_samples():
    """Ineichen GHI at a fixed TL across zenith, elevation and day of year."""
    out = []
    for doy_ts in ('2026-01-15T20:00:00Z', '2026-06-21T20:00:00Z', '2026-10-03T21:00:00Z'):
        for elev in (0.0, 121.0, 1500.0):
            for app_zen in (0.0, 30.0, 60.0, 80.0, 85.0, 88.0, 89.5, 90.0, 91.0):
                for tl in (2.0, 3.2615, 5.0):
                    idx = pd.DatetimeIndex([pd.Timestamp(doy_ts)])
                    am_rel = pvlib.atmosphere.get_relative_airmass(np.array([app_zen]), 'kastenyoung1989')
                    am_abs = pvlib.atmosphere.get_absolute_airmass(am_rel, pvlib.atmosphere.alt2pres(elev))
                    dni_extra = pvlib.irradiance.get_extra_radiation(idx)
                    cs = pvlib.clearsky.ineichen(np.array([app_zen]), am_abs, tl, altitude=elev,
                                                 dni_extra=np.asarray(dni_extra))
                    ghi = float(np.asarray(cs['ghi'])[0])
                    out.append({'utc': doy_ts, 'elevation': elev, 'apparentZenith': app_zen, 'tl': tl,
                                'dniExtra': float(np.asarray(dni_extra)[0]), 'ghi': 0.0 if math.isnan(ghi) else ghi})
    return out


def turbidity_samples(table):
    out = []
    pts = [(37.70, -122.05), (40.0, -105.0), (25.5, -80.5), (61.2, -149.9), (21.3, -157.8),
           (18.4, -66.1), (47.6, -122.3), (33.4, -112.0), (44.0, -71.0), (30.0, -90.0)]
    for lat, lon in pts:
        for ts in ('2026-01-01T12:00:00Z', '2026-01-20T12:00:00Z', '2026-02-29T12:00:00Z'.replace('2026', '2028'),
                   '2026-07-04T12:00:00Z', '2026-10-03T06:59:00Z', '2026-10-03T07:00:00Z', '2026-12-25T12:00:00Z'):
            idx = pd.DatetimeIndex([pd.Timestamp(ts)])
            out.append({'lat': lat, 'lon': lon, 'utc': ts,
                        'table': float(table_tl_series(table, lat, lon, idx).iloc[0]),
                        'native': float(pvlib.clearsky.lookup_linke_turbidity(idx, lat, lon).iloc[0])})
    return out


def main():
    write('packages/core/src/heat/spaTables.js', spa_tables())

    table, rows, cols = turbidity_table()
    assert (rows, cols) == (114, 240), (rows, cols)
    write('packages/core/src/heat/data/linkeTurbidity-nws-0p5deg.bin',
          np.ascontiguousarray(table.transpose(2, 0, 1)).tobytes())

    grid = fixture()
    grid['properties'] = {**FIXTURE_META, **grid['properties']}
    write('tests/fixtures/heat/gridpoint-mtr-2026-10-03.json', json.dumps(grid, indent=2) + '\n')

    ref_doc = {
        'generator': 'scripts/heat/generate_heat_reference.py',
        'pvlib': pvlib.__version__,
        'numpy': np.__version__,
        'pandas': pd.__version__,
        'day': '2026-10-03',
        'timeZone': ref.TZ,
        'elevationM': 121.0,
        'roundedCategory1': {'native': run_reference(None, 1), 'table': run_reference(table, 1)},
        'unrounded': unrounded_rows(table),
        'solar': solar_samples(),
        'clearSky': clearsky_samples(),
        'turbidity': turbidity_samples(table),
        'tableBox': {'north': TL_NORTH, 'south': TL_SOUTH, 'west': TL_WEST, 'east': TL_EAST,
                     'resolution': TL_RES, 'rows': rows, 'cols': cols},
    }
    write('tests/fixtures/heat/heatReference.json', json.dumps(ref_doc, indent=1) + '\n')


if __name__ == '__main__':
    main()
