export const teamSummarySnapshot = {
  generatedAt: '2024-07-15T12:00:00Z',
  totals: {
    divisions: 3,
    teams: 9,
    playersAssigned: 98,
    overflowPlayers: 4,
    divisionsNeedingCoaches: 1,
    divisionsWithOpenRosterSlots: 2,
  },
  divisions: [
    {
      divisionId: 'U8',
      totalTeams: 3,
      playersAssigned: 30,
      totalCapacity: 36,
      averageFillRate: 0.8333,
      teamsNeedingPlayers: ['U8-T01', 'U8-T02'],
      slotsRemaining: 6,
      needsAdditionalCoaches: false,
      coachCoverage: {
        totalTeams: 3,
        volunteerCoaches: 3,
        teamsWithCoach: 3,
        teamsWithoutCoach: 0,
        coverageRate: 1,
        needsAdditionalCoaches: false,
      },
      mutualBuddyPairs: 4,
      unmatchedBuddyCount: 1,
      unmatchedBuddyReasons: {
        'not-reciprocated': 1,
      },
      overflowUnits: 1,
      overflowPlayers: 2,
      overflowByReason: {
        'insufficient-capacity': 1,
      },
      overflowPlayersByReason: {
        'insufficient-capacity': 2,
      },
    },
    {
      divisionId: 'U10',
      totalTeams: 4,
      playersAssigned: 44,
      totalCapacity: 48,
      averageFillRate: 0.9167,
      teamsNeedingPlayers: ['U10-T03'],
      slotsRemaining: 4,
      needsAdditionalCoaches: true,
      coachCoverage: {
        totalTeams: 4,
        volunteerCoaches: 3,
        teamsWithCoach: 3,
        teamsWithoutCoach: 1,
        coverageRate: 0.75,
        needsAdditionalCoaches: true,
      },
      mutualBuddyPairs: 5,
      unmatchedBuddyCount: 2,
      unmatchedBuddyReasons: {
        'missing-player': 1,
        'not-reciprocated': 1,
      },
      overflowUnits: 1,
      overflowPlayers: 2,
      overflowByReason: {
        'coach-capacity': 1,
      },
      overflowPlayersByReason: {
        'coach-capacity': 2,
      },
    },
    {
      divisionId: 'U12',
      totalTeams: 2,
      playersAssigned: 24,
      totalCapacity: 24,
      averageFillRate: 1,
      teamsNeedingPlayers: [],
      slotsRemaining: 0,
      needsAdditionalCoaches: false,
      coachCoverage: {
        totalTeams: 2,
        volunteerCoaches: 2,
        teamsWithCoach: 2,
        teamsWithoutCoach: 0,
        coverageRate: 1,
        needsAdditionalCoaches: false,
      },
      mutualBuddyPairs: 2,
      unmatchedBuddyCount: 0,
      unmatchedBuddyReasons: {},
      overflowUnits: 0,
      overflowPlayers: 0,
      overflowByReason: {},
      overflowPlayersByReason: {},
    },
  ],
};
