export const teamPersistenceSnapshot = {
  lastSyncedAt: '2024-07-15T13:12:00Z',
  lastRunId: 'run-2024-fall-initial',
  preparedTeamRows: 9,
  preparedPlayerRows: 98,
  pendingManualOverrideGoal: 'Confirm coach assignments for two teams before the next sync.',
  manualOverrides: [
    {
      id: 'override-u8-name',
      teamId: 'U8-T01',
      teamName: 'U8 Lightning',
      field: 'name',
      value: 'U8 Lightning – Blue',
      status: 'pending',
      updatedAt: '2024-07-15T12:41:00Z',
      reason: 'Coach requested jersey color indicator.',
    },
    {
      id: 'override-u10-coach',
      teamId: 'U10-T03',
      teamName: 'U10 Storm',
      field: 'coachId',
      value: 'coach-8891',
      status: 'pending',
      updatedAt: '2024-07-15T12:39:00Z',
      reason: 'Volunteer onboarding is finishing background check.',
    },
    {
      id: 'override-u10-name',
      teamId: 'U10-T02',
      teamName: 'U10 Comets',
      field: 'name',
      value: 'U10 Comets – Gold',
      status: 'applied',
      updatedAt: '2024-07-15T11:55:00Z',
      reason: 'Align name with practice jerseys.',
    },
    {
      id: 'override-u12-coach',
      teamId: 'U12-T01',
      teamName: 'U12 Falcons',
      field: 'coachId',
      value: 'coach-4472',
      status: 'applied',
      updatedAt: '2024-07-15T11:32:00Z',
      reason: 'Coach assignment confirmed via Supabase sync.',
    },
  ],
  runHistory: [
    {
      runId: 'run-2024-fall-initial',
      status: 'success',
      triggeredBy: 'scheduler-bot',
      startedAt: '2024-07-15T12:05:00Z',
      completedAt: '2024-07-15T12:07:00Z',
      updatedTeams: 9,
      updatedPlayers: 98,
      notes: 'Initial deterministic UUID mapping seeded.',
    },
    {
      runId: 'run-2024-fall-sanity',
      status: 'success',
      triggeredBy: 'admin-review',
      startedAt: '2024-07-14T20:10:00Z',
      completedAt: '2024-07-14T20:12:00Z',
      updatedTeams: 9,
      updatedPlayers: 98,
      notes: 'Manual override validation dry-run.',
    },
    {
      runId: 'run-2024-fall-prep',
      status: 'blocked',
      triggeredBy: 'admin-review',
      startedAt: '2024-07-13T19:05:00Z',
      completedAt: '2024-07-13T19:05:00Z',
      updatedTeams: 0,
      updatedPlayers: 0,
      notes: 'Roster overrides missing required coach assignments.',
    },
  ],
};
